output:
  sort-results: true

run:
  timeout: 5m
  build-tags:
    - integration
    - e2e
  skip-dirs:
    # Skip all Go code in Tilt modules directory if any.
    - tilt_modules

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  goheader:
    template: |-
      Copyright {{ YEAR }} New Relic Corporation. All rights reserved.
      SPDX-License-Identifier: Apache-2.0
  gci:
    local-prefixes: github.com/newrelic/newrelic-infra-operator

# Update list of enabled linters using 'make update-linters'.
linters:
  disable-all: false
  disable:
    # TODOs in the code are OK.
    - godox
    # We do not have clearly defined error types yet.
    - goerr113
    # We do not require all used structs to have all fields initialized.
    - exhaustivestruct
    # This linters has been deprecated.
    - interfacer
    - maligned
    - scopelint
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - ifshort
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - stylecheck
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
