FROM golang:1.19-alpine3.15 as builder

RUN apk add -U make

WORKDIR /usr/src/newrelic-infra-operator

COPY go.mod .

RUN go mod download

COPY . .

RUN make

FROM alpine:3.18.2

COPY --from=builder /usr/src/newrelic-infra-operator/newrelic-infra-operator /usr/local/bin/

ENTRYPOINT ["newrelic-infra-operator"]
