{{- $licenseKey := include "newrelic.common.license._licenseKey" . -}}
{{- if $licenseKey }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "newrelic-infra-operator.fullname.license" . }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
type: Opaque
data:
  license: {{ $licenseKey | b64enc }}
{{- end }}
