apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "newrelic.common.naming.fullname" . }}
  labels:
    {{- include "newrelic-infra-operator.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    {{- include "newrelic-infra-operator.appLabel" . | nindent 4 }}
