{{- if (and (not .Values.customTLSCertificate) (not .Values.certManager.enabled)) }}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "newrelic.common.naming.fullname" . }}-admission-create
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ include "newrelic.common.naming.name" $ }}-admission-create
{{ include "newrelic.common.labels" $ | indent 4 }}
spec:
  template:
    metadata:
      name: {{ include "newrelic.common.naming.fullname" . }}-admission-create
      labels:
        app: {{ include "newrelic.common.naming.name" $ }}-admission-create
{{ include "newrelic.common.labels" $ | indent 8 }}
    spec:
      {{- if .Values.admissionWebhooksPatchJob.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.admissionWebhooksPatchJob.image.pullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: create
          image: {{ .Values.admissionWebhooksPatchJob.image.repository }}:{{ .Values.admissionWebhooksPatchJob.image.tag }}
          imagePullPolicy: {{ .Values.admissionWebhooksPatchJob.image.pullPolicy }}
          args:
            - create
            - --host={{ include "newrelic.common.naming.fullname" . }},{{ include "newrelic.common.naming.fullname" . }}.{{ .Release.Namespace }}.svc
            - --namespace={{ .Release.Namespace }}
            - --secret-name={{ include "newrelic.common.naming.fullname" . }}-admission
            - --cert-name=tls.crt
            - --key-name=tls.key
          {{- if .Values.admissionWebhooksPatchJob.image.volumeMounts }}
          volumeMounts:
          {{- include "tplvalues.render" ( dict "value" .Values.admissionWebhooksPatchJob.image.volumeMounts "context" $ ) | nindent 10 }}
          {{- end }}
      {{- if .Values.admissionWebhooksPatchJob.image.volumes }}
      volumes:
      {{- include "tplvalues.render" ( dict "value" .Values.admissionWebhooksPatchJob.image.volumes "context" $ ) | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "newrelic.common.naming.fullname" . }}-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
{{- end }}
